"""add_candlestick_patterns_table

Revision ID: 961ff06aba8d
Revises: 313f67cf0c5d
Create Date: 2025-12-11 21:08:58.014592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961ff06aba8d'
down_revision = '313f67cf0c5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candlestick_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('candles_indices', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('pattern_zone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pattern_active', 'candlestick_patterns', ['is_active'], unique=False)
    op.create_index('idx_pattern_symbol_tf', 'candlestick_patterns', ['symbol', 'timeframe'], unique=False)
    op.create_index('idx_pattern_symbol_tf_ts', 'candlestick_patterns', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_candlestick_patterns_id'), 'candlestick_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_candlestick_patterns_symbol'), 'candlestick_patterns', ['symbol'], unique=False)
    op.create_index(op.f('ix_candlestick_patterns_timeframe'), 'candlestick_patterns', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candlestick_patterns_timestamp'), 'candlestick_patterns', ['timestamp'], unique=False)
    op.create_index('idx_ohlcv_timestamp', 'ohlcv', ['timestamp'], unique=False)
    op.create_index(op.f('ix_signal_live_logs_id'), 'signal_live_logs', ['id'], unique=False)
    op.alter_column('signals', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signals', 'archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_signal_live_logs_id'), table_name='signal_live_logs')
    op.drop_index('idx_ohlcv_timestamp', table_name='ohlcv')
    op.drop_index(op.f('ix_candlestick_patterns_timestamp'), table_name='candlestick_patterns')
    op.drop_index(op.f('ix_candlestick_patterns_timeframe'), table_name='candlestick_patterns')
    op.drop_index(op.f('ix_candlestick_patterns_symbol'), table_name='candlestick_patterns')
    op.drop_index(op.f('ix_candlestick_patterns_id'), table_name='candlestick_patterns')
    op.drop_index('idx_pattern_symbol_tf_ts', table_name='candlestick_patterns')
    op.drop_index('idx_pattern_symbol_tf', table_name='candlestick_patterns')
    op.drop_index('idx_pattern_active', table_name='candlestick_patterns')
    op.drop_table('candlestick_patterns')
    # ### end Alembic commands ###

