"""Initial migration

Revision ID: ef922a450a11
Revises: 
Create Date: 2025-11-05 21:40:40.804065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef922a450a11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_pairs_id'), 'trading_pairs', ['id'], unique=False)
    op.create_index(op.f('ix_trading_pairs_symbol'), 'trading_pairs', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('analysis_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('ema20', sa.Float(), nullable=True),
    sa.Column('ema50', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('candles_data', sa.JSON(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_pair_timeframe', 'analysis_data', ['pair_id', 'timeframe', 'analyzed_at'], unique=False)
    op.create_index(op.f('ix_analysis_data_analyzed_at'), 'analysis_data', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_analysis_data_id'), 'analysis_data', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_data_pair_id'), 'analysis_data', ['pair_id'], unique=False)
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('level_type', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('test_count', sa.Integer(), nullable=True),
    sa.Column('strength', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_touch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_touch', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_levels_active', 'levels', ['is_active', 'pair_id'], unique=False)
    op.create_index('idx_levels_pair_price', 'levels', ['pair_id', 'price'], unique=False)
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_index(op.f('ix_levels_is_active'), 'levels', ['is_active'], unique=False)
    op.create_index(op.f('ix_levels_pair_id'), 'levels', ['pair_id'], unique=False)
    op.create_index(op.f('ix_levels_price'), 'levels', ['price'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('level_price', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trend_1h', sa.String(length=20), nullable=True),
    sa.Column('level_type', sa.String(length=20), nullable=True),
    sa.Column('test_count', sa.Integer(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percent', sa.Float(), nullable=True),
    sa.Column('max_profit', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['trading_pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_pair_timestamp', 'signals', ['pair_id', 'timestamp'], unique=False)
    op.create_index('idx_signals_status', 'signals', ['status'], unique=False)
    op.create_index('idx_signals_type', 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_pair_id'), 'signals', ['pair_id'], unique=False)
    op.create_index(op.f('ix_signals_signal_type'), 'signals', ['signal_type'], unique=False)
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.drop_index(op.f('ix_signals_signal_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_pair_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index('idx_signals_type', table_name='signals')
    op.drop_index('idx_signals_status', table_name='signals')
    op.drop_index('idx_signals_pair_timestamp', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_levels_price'), table_name='levels')
    op.drop_index(op.f('ix_levels_pair_id'), table_name='levels')
    op.drop_index(op.f('ix_levels_is_active'), table_name='levels')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_index('idx_levels_pair_price', table_name='levels')
    op.drop_index('idx_levels_active', table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_analysis_data_pair_id'), table_name='analysis_data')
    op.drop_index(op.f('ix_analysis_data_id'), table_name='analysis_data')
    op.drop_index(op.f('ix_analysis_data_analyzed_at'), table_name='analysis_data')
    op.drop_index('idx_analysis_pair_timeframe', table_name='analysis_data')
    op.drop_table('analysis_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trading_pairs_symbol'), table_name='trading_pairs')
    op.drop_index(op.f('ix_trading_pairs_id'), table_name='trading_pairs')
    op.drop_table('trading_pairs')
    # ### end Alembic commands ###

