"""add_chart_patterns_table

Revision ID: f04cecdee35b
Revises: 961ff06aba8d
Create Date: 2025-01-11 22:05:53.888194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f04cecdee35b'
down_revision = '961ff06aba8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_category', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('support_level', sa.Float(), nullable=True),
    sa.Column('resistance_level', sa.Float(), nullable=True),
    sa.Column('neckline', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('pattern_height', sa.Float(), nullable=True),
    sa.Column('pattern_width', sa.Integer(), nullable=True),
    sa.Column('volume_confirmation', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('candles_count', sa.Integer(), nullable=True),
    sa.Column('pattern_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chart_pattern_symbol_tf', 'chart_patterns', ['symbol', 'timeframe'], unique=False)
    op.create_index('idx_chart_pattern_active', 'chart_patterns', ['is_active'], unique=False)
    op.create_index('idx_chart_pattern_confirmed', 'chart_patterns', ['is_confirmed'], unique=False)
    op.create_index('idx_chart_pattern_start_time', 'chart_patterns', ['start_time'], unique=False)
    op.create_index(op.f('ix_chart_patterns_id'), 'chart_patterns', ['id'], unique=False)
    op.create_index(op.f('ix_chart_patterns_symbol'), 'chart_patterns', ['symbol'], unique=False)
    op.create_index(op.f('ix_chart_patterns_timeframe'), 'chart_patterns', ['timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chart_patterns_timeframe'), table_name='chart_patterns')
    op.drop_index(op.f('ix_chart_patterns_symbol'), table_name='chart_patterns')
    op.drop_index(op.f('ix_chart_patterns_id'), table_name='chart_patterns')
    op.drop_index('idx_chart_pattern_start_time', table_name='chart_patterns')
    op.drop_index('idx_chart_pattern_confirmed', table_name='chart_patterns')
    op.drop_index('idx_chart_pattern_active', table_name='chart_patterns')
    op.drop_index('idx_chart_pattern_symbol_tf', table_name='chart_patterns')
    op.drop_table('chart_patterns')
    # ### end Alembic commands ###
